### ISSUE TITLE
关于tab字段的疑问

### ISSUE THREAD

**Issue by crazyString** [chongminggao/KuaiRand#1]
您好！
我注意到数据集中的“tab”字段的取值范围是从0到14。为了更好地理解这些数据，我想了解每个取值所对应的具体场景。另外，我特别好奇在双栏布局场景和沉浸式视频流中，这个“tab”字段通常是什么取值？
期待您的解答，谢谢！

**Comment by chongminggao** [comment]
您好，您可以统计一下，有两个tab值是最多的。其中第一多的是快手主界面单列的场景，第二多的是快手主界面双列场景。其次13个场景具体的对应我也不太清楚，包括各种软件中的界面，包括电脑网页端、微信小程序等等场景。这些场景可能由于用户群体、或者场景特性，推荐策略会有微妙区别。例如我本人看B站比较多，能明显发现B站的网页端与手机平板端的推荐列表完全不一致。快手下各个场景可能也存在一些区别。由于我不是业务端人员，也没有深入使用感受过，所以不敢下定论。
